### ISSUE TITLE
added ingredient / unit form is not adding below the extra ingredient / unit form

### ISSUE THREAD

**Issue by StrangerXDD** [pumasa/Agile-Project#53]
added ingredient / unit form is not adding below the extra ingredient / unit form, see below insrtuction
![bug2](https://user-images.githubusercontent.com/91754279/168917531-24a4afaf-c557-430e-a1d6-3ef277bde19f.PNG)
![bug3](https://user-images.githubusercontent.com/91754279/168917537-775e68c3-4309-4d54-a123-c40221f322d3.PNG)

**Comment by GurpreetSingh2601** [comment]
Done

**Comment by GurpreetSingh2601** [comment]
Done
